name: PR Preview - Publish
on:
  workflow_run:
    workflows: ["PR Preview - Build"]
    types: [completed]
permissions:
  contents: write
  pull-requests: write
jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
    uses: WordPress/action-wp-playground-pr-preview/.github/workflows/preview-publish.yml@v3
    with:
      blueprint: |
        {
          "$schema": "https://playground.wordpress.net/blueprint-schema.json",
          "preferredVersions": { "php": "8.2", "wp": "latest" },
          "steps": [
            { "step": "login" },
            {
              "step": "installPlugin",
              "pluginData": { "resource": "url", "url": "{{ARTIFACT_URL:plugin-zip}}" },
              "options": { "activate": true }
            }
          ]
        }
